"""User publisher affinity generator for participant solution."""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.platform.core.dataset import Dataset


class UserPublisherGenerator:
    """Generate candidates from user publisher preference profiles.

    Expands publisher-level affinity into concrete edition candidates by
    weighting editions from preferred publishers by their temporal popularity.
    Blends full-history and recent-window profiles to balance long-term loyalty
    with short-term publisher engagement. Seen positives are filtered before
    top-k truncation to maximise novel candidate recall.
    """

    name = "user_publisher"

    def __init__(
        self,
        publisher_smoothing: float = 0.5,
        recency_weight: float = 0.4,
        show_progress: bool = False,
    ) -> None:
        """Store hyperparameters for publisher-based candidate scoring.

        Args:
            publisher_smoothing: Additive prior applied to per-edition popularity.
            recency_weight: Blend weight for recent profile (0 = full-history
                only, 1 = recent only).
            show_progress: Retained for API compatibility.
        """
        self.publisher_smoothing = publisher_smoothing
        self.recency_weight = float(np.clip(recency_weight, 0.0, 1.0))
        self.show_progress = show_progress

    def generate(
        self,
        dataset: Dataset,
        user_ids: np.ndarray,
        features: pd.DataFrame,
        k: int,
        seed: int,
    ) -> pd.DataFrame:
        """Emit top-k publisher-affinity candidates per user.

        Args:
            dataset: Runtime dataset with catalog and seen-positive pairs.
            user_ids: Target users for candidate generation.
            features: Long feature table with user publisher profiles.
            k: Maximum candidates per user generated by this source.
            seed: Pipeline seed (unused by this deterministic generator).

        Returns:
            Candidate DataFrame with required schema and source name.
        """
        del seed

        full_profile = features[features["feature_type"] == "user_publisher_profile"][
            ["user_id", "publisher_id", "value"]
        ].rename(columns={"value": "weight"})
        recent_profile = features[
            features["feature_type"] == "user_publisher_profile_recent"
        ][["user_id", "publisher_id", "value"]].rename(columns={"value": "weight"})

        parts: list[pd.DataFrame] = []
        if not full_profile.empty:
            fp = full_profile.copy()
            fp["weight"] = fp["weight"] * (1.0 - self.recency_weight)
            parts.append(fp)
        if not recent_profile.empty:
            rp = recent_profile.copy()
            rp["weight"] = rp["weight"] * self.recency_weight
            parts.append(rp)

        if not parts:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        user_profile = (
            pd.concat(parts, ignore_index=True)
            .groupby(["user_id", "publisher_id"], as_index=False)["weight"]
            .sum()
        )
        user_profile = user_profile[user_profile["user_id"].isin(user_ids)]
        if user_profile.empty:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        pop_df = pd.DataFrame()
        for pop_type in (
            "edition_popularity_weighted",
            "edition_popularity_w30",
            "edition_popularity_all",
        ):
            pop_df = features[features["feature_type"] == pop_type][
                ["edition_id", "value"]
            ].rename(columns={"value": "pop"})
            if not pop_df.empty:
                break

        publisher_editions = dataset.catalog_df[["edition_id", "publisher_id"]].copy()
        if not pop_df.empty:
            publisher_editions = publisher_editions.merge(pop_df, on="edition_id", how="left")
            publisher_editions["pop"] = publisher_editions["pop"].fillna(0.0)
        else:
            publisher_editions["pop"] = 0.0

        top_per_publisher = max(k * 5, 200)
        top_publisher_editions = (
            publisher_editions.sort_values(
                ["publisher_id", "pop", "edition_id"], ascending=[True, False, True]
            )
            .groupby("publisher_id", group_keys=False)
            .head(top_per_publisher)[["publisher_id", "edition_id", "pop"]]
        )

        merged = user_profile.merge(top_publisher_editions, on="publisher_id", how="inner")
        if merged.empty:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        merged["score"] = merged["weight"] * (merged["pop"] + self.publisher_smoothing)
        result = merged.groupby(["user_id", "edition_id"], as_index=False)["score"].sum()

        seen = dataset.seen_positive_df[["user_id", "edition_id"]].drop_duplicates()
        result = result.merge(seen.assign(_seen=1), on=["user_id", "edition_id"], how="left")
        result = result[result["_seen"].isna()].drop(columns=["_seen"])

        result = result.sort_values(
            ["user_id", "score", "edition_id"], ascending=[True, False, True]
        )
        result = result.groupby("user_id", group_keys=False).head(k)
        result["source"] = self.name
        return result[["user_id", "edition_id", "score", "source"]].reset_index(drop=True)
