"""User language affinity generator for participant solution."""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.platform.core.dataset import Dataset


class UserLanguageGenerator:
    """Generate candidates from user language preference profiles.

    Expands language-level affinity (both full-history and recent-window) into
    concrete edition candidates by weighting editions within preferred languages
    by their temporal popularity. Language preference is a strong filter signal:
    users rarely switch reading languages, so this generator provides high-
    precision recall with low noise.

    The generator blends full-history and recent profiles with a configurable
    recency_weight (0 = full-history only, 1 = recent only, 0.5 = equal blend).
    Seen positives are filtered before top-k truncation.
    """

    name = "user_language"

    def __init__(
        self,
        language_smoothing: float = 0.5,
        recency_weight: float = 0.4,
        show_progress: bool = False,
    ) -> None:
        """Store hyperparameters for language-based candidate scoring.

        Args:
            language_smoothing: Additive prior applied to per-edition popularity.
            recency_weight: Blend weight for recent profile vs full-history
                profile. 0 = full-history only, 1 = recent only.
            show_progress: Retained for API compatibility.
        """
        self.language_smoothing = language_smoothing
        self.recency_weight = float(np.clip(recency_weight, 0.0, 1.0))
        self.show_progress = show_progress

    def generate(
        self,
        dataset: Dataset,
        user_ids: np.ndarray,
        features: pd.DataFrame,
        k: int,
        seed: int,
    ) -> pd.DataFrame:
        """Emit top-k language-affinity candidates per user.

        Args:
            dataset: Runtime dataset with catalog and seen-positive pairs.
            user_ids: Target users for candidate generation.
            features: Long feature table with user language profiles.
            k: Maximum candidates per user generated by this source.
            seed: Pipeline seed (unused by this deterministic generator).

        Returns:
            Candidate DataFrame with required schema and source name.
        """
        del seed

        full_profile = features[features["feature_type"] == "user_language_profile"][
            ["user_id", "language_id", "value"]
        ].rename(columns={"value": "weight"})
        recent_profile = features[features["feature_type"] == "user_language_profile_recent"][
            ["user_id", "language_id", "value"]
        ].rename(columns={"value": "weight"})

        parts: list[pd.DataFrame] = []
        if not full_profile.empty:
            fp = full_profile.copy()
            fp["weight"] = fp["weight"] * (1.0 - self.recency_weight)
            parts.append(fp)
        if not recent_profile.empty:
            rp = recent_profile.copy()
            rp["weight"] = rp["weight"] * self.recency_weight
            parts.append(rp)

        if not parts:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        user_profile = (
            pd.concat(parts, ignore_index=True)
            .groupby(["user_id", "language_id"], as_index=False)["weight"]
            .sum()
        )
        user_profile = user_profile[user_profile["user_id"].isin(user_ids)]
        if user_profile.empty:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        pop_df = pd.DataFrame()
        for pop_type in (
            "edition_popularity_weighted",
            "edition_popularity_w30",
            "edition_popularity_all",
        ):
            pop_df = features[features["feature_type"] == pop_type][
                ["edition_id", "value"]
            ].rename(columns={"value": "pop"})
            if not pop_df.empty:
                break

        language_editions = dataset.catalog_df[["edition_id", "language_id"]].copy()
        if not pop_df.empty:
            language_editions = language_editions.merge(pop_df, on="edition_id", how="left")
            language_editions["pop"] = language_editions["pop"].fillna(0.0)
        else:
            language_editions["pop"] = 0.0

        top_per_language = max(k * 5, 200)
        top_language_editions = (
            language_editions.sort_values(
                ["language_id", "pop", "edition_id"], ascending=[True, False, True]
            )
            .groupby("language_id", group_keys=False)
            .head(top_per_language)[["language_id", "edition_id", "pop"]]
        )

        merged = user_profile.merge(top_language_editions, on="language_id", how="inner")
        if merged.empty:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        merged["score"] = merged["weight"] * (merged["pop"] + self.language_smoothing)
        result = merged.groupby(["user_id", "edition_id"], as_index=False)["score"].sum()

        seen = dataset.seen_positive_df[["user_id", "edition_id"]].drop_duplicates()
        result = result.merge(seen.assign(_seen=1), on=["user_id", "edition_id"], how="left")
        result = result[result["_seen"].isna()].drop(columns=["_seen"])

        result = result.sort_values(
            ["user_id", "score", "edition_id"], ascending=[True, False, True]
        )
        result = result.groupby("user_id", group_keys=False).head(k)
        result["source"] = self.name
        return result[["user_id", "edition_id", "score", "source"]].reset_index(drop=True)
